on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write # <--- CRITICAL: Permission to verify the runner
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   To install LaTeX to build PDF book 
        #   tinytex: true 
        #   uncomment below and fill to pin a version
        #   version: pre-release
          
      # - name: Setup Python
      #   uses: actions/setup-python@v4.1.0
            
      # add software dependencies here
      
      # - name: Install python dependencies
      #   run: |
      #     python -m pip install jupyter
      #     python -m pip install numpy
      #     python -m pip install matplotlib

      # a "super-command." It performs the render step internally before it starts the publish step.
      - name: Render and Publish Quarto Project
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: github-pages # <--- CRITICAL: Use the "Modern" Artifact method

      # "Don't bother saving the website files into a branch like gh-pages. Just bundle them up and hand them directly to the GitHub Pages engine."
      #  This below is the old way
      #- name: Deploy ðŸš€
      #  if: github.event_name != 'pull_request'
      #  uses: JamesIves/github-pages-deploy-action@v4.5.0
      #  with:
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: _site # The folder the action should deploy.
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
